output_dir: $SCRATCH/agu19-dl-tutorial/climseg-test

data:
    name: cam
    train_dir: /global/cscratch1/sd/sfarrell/climate-seg-benchmark/data/climseg_data/train
    valid_dir: /global/cscratch1/sd/sfarrell/climate-seg-benchmark/data/climseg_data/validation
    n_train: 2048
    n_valid: 256
    batch_size: 1

model:
    name: unet
    input_shape: [768, 1152, 16]
    n_classes: 3

optimizer:
    name: Adam
    lr: 0.001

train:
    loss: sparse_categorical_crossentropy
    n_epochs: 32
